// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.22.0
// source: proto/card-payment/cardPayment.proto

package card_payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber    string                 `protobuf:"bytes,1,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	TransactionType string                 `protobuf:"bytes,2,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	Iso             string                 `protobuf:"bytes,3,opt,name=iso,proto3" json:"iso,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_card_payment_cardPayment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_payment_cardPayment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_card_payment_cardPayment_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Request) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *Request) GetIso() string {
	if x != nil {
		return x.Iso
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Iso           string                 `protobuf:"bytes,3,opt,name=iso,proto3" json:"iso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_card_payment_cardPayment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_payment_cardPayment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_card_payment_cardPayment_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetIso() string {
	if x != nil {
		return x.Iso
	}
	return ""
}

var File_proto_card_payment_cardPayment_proto protoreflect.FileDescriptor

const file_proto_card_payment_cardPayment_proto_rawDesc = "" +
	"\n" +
	"$proto/card-payment/cardPayment.proto\x12\vcardPayment\"i\n" +
	"\aRequest\x12\"\n" +
	"\fserialNumber\x18\x01 \x01(\tR\fserialNumber\x12(\n" +
	"\x0ftransactionType\x18\x02 \x01(\tR\x0ftransactionType\x12\x10\n" +
	"\x03iso\x18\x03 \x01(\tR\x03iso\"N\n" +
	"\bResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03iso\x18\x03 \x01(\tR\x03iso2P\n" +
	"\x12CardPaymentService\x12:\n" +
	"\vTransaction\x12\x14.cardPayment.Request\x1a\x15.cardPayment.ResponseB\x16Z\x14./proto/card-paymentb\x06proto3"

var (
	file_proto_card_payment_cardPayment_proto_rawDescOnce sync.Once
	file_proto_card_payment_cardPayment_proto_rawDescData []byte
)

func file_proto_card_payment_cardPayment_proto_rawDescGZIP() []byte {
	file_proto_card_payment_cardPayment_proto_rawDescOnce.Do(func() {
		file_proto_card_payment_cardPayment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_card_payment_cardPayment_proto_rawDesc), len(file_proto_card_payment_cardPayment_proto_rawDesc)))
	})
	return file_proto_card_payment_cardPayment_proto_rawDescData
}

var file_proto_card_payment_cardPayment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_card_payment_cardPayment_proto_goTypes = []any{
	(*Request)(nil),  // 0: cardPayment.Request
	(*Response)(nil), // 1: cardPayment.Response
}
var file_proto_card_payment_cardPayment_proto_depIdxs = []int32{
	0, // 0: cardPayment.CardPaymentService.Transaction:input_type -> cardPayment.Request
	1, // 1: cardPayment.CardPaymentService.Transaction:output_type -> cardPayment.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_card_payment_cardPayment_proto_init() }
func file_proto_card_payment_cardPayment_proto_init() {
	if File_proto_card_payment_cardPayment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_card_payment_cardPayment_proto_rawDesc), len(file_proto_card_payment_cardPayment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_card_payment_cardPayment_proto_goTypes,
		DependencyIndexes: file_proto_card_payment_cardPayment_proto_depIdxs,
		MessageInfos:      file_proto_card_payment_cardPayment_proto_msgTypes,
	}.Build()
	File_proto_card_payment_cardPayment_proto = out.File
	file_proto_card_payment_cardPayment_proto_goTypes = nil
	file_proto_card_payment_cardPayment_proto_depIdxs = nil
}
