// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.22.0
// source: proto/qr-notif/qrNotif.proto

package qr_notif

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_qr_notif_qrNotif_proto protoreflect.FileDescriptor

const file_proto_qr_notif_qrNotif_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/qr-notif/qrNotif.proto\x12\aqrNotif\x1a\x1cgoogle/protobuf/struct.proto2L\n" +
	"\x0eQrNotifService\x12:\n" +
	"\x06Status\x12\x17.google.protobuf.Struct\x1a\x17.google.protobuf.StructB\x12Z\x10./proto/qr-notifb\x06proto3"

var file_proto_qr_notif_qrNotif_proto_goTypes = []any{
	(*structpb.Struct)(nil), // 0: google.protobuf.Struct
}
var file_proto_qr_notif_qrNotif_proto_depIdxs = []int32{
	0, // 0: qrNotif.QrNotifService.Status:input_type -> google.protobuf.Struct
	0, // 1: qrNotif.QrNotifService.Status:output_type -> google.protobuf.Struct
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_qr_notif_qrNotif_proto_init() }
func file_proto_qr_notif_qrNotif_proto_init() {
	if File_proto_qr_notif_qrNotif_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qr_notif_qrNotif_proto_rawDesc), len(file_proto_qr_notif_qrNotif_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_qr_notif_qrNotif_proto_goTypes,
		DependencyIndexes: file_proto_qr_notif_qrNotif_proto_depIdxs,
	}.Build()
	File_proto_qr_notif_qrNotif_proto = out.File
	file_proto_qr_notif_qrNotif_proto_goTypes = nil
	file_proto_qr_notif_qrNotif_proto_depIdxs = nil
}
