// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.22.0
// source: proto/mini-atm/miniAtm.proto

package mini_atm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MiniAtmService_Transaction_FullMethodName = "/miniAtm.MiniAtmService/Transaction"
)

// MiniAtmServiceClient is the client API for MiniAtmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MiniAtmServiceClient interface {
	Transaction(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type miniAtmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMiniAtmServiceClient(cc grpc.ClientConnInterface) MiniAtmServiceClient {
	return &miniAtmServiceClient{cc}
}

func (c *miniAtmServiceClient) Transaction(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MiniAtmService_Transaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiniAtmServiceServer is the server API for MiniAtmService service.
// All implementations must embed UnimplementedMiniAtmServiceServer
// for forward compatibility.
type MiniAtmServiceServer interface {
	Transaction(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedMiniAtmServiceServer()
}

// UnimplementedMiniAtmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiniAtmServiceServer struct{}

func (UnimplementedMiniAtmServiceServer) Transaction(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transaction not implemented")
}
func (UnimplementedMiniAtmServiceServer) mustEmbedUnimplementedMiniAtmServiceServer() {}
func (UnimplementedMiniAtmServiceServer) testEmbeddedByValue()                        {}

// UnsafeMiniAtmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiniAtmServiceServer will
// result in compilation errors.
type UnsafeMiniAtmServiceServer interface {
	mustEmbedUnimplementedMiniAtmServiceServer()
}

func RegisterMiniAtmServiceServer(s grpc.ServiceRegistrar, srv MiniAtmServiceServer) {
	// If the following call pancis, it indicates UnimplementedMiniAtmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MiniAtmService_ServiceDesc, srv)
}

func _MiniAtmService_Transaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAtmServiceServer).Transaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAtmService_Transaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAtmServiceServer).Transaction(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MiniAtmService_ServiceDesc is the grpc.ServiceDesc for MiniAtmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiniAtmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "miniAtm.MiniAtmService",
	HandlerType: (*MiniAtmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transaction",
			Handler:    _MiniAtmService_Transaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mini-atm/miniAtm.proto",
}
